name: CMake Cross-Platform

on:
  push:
    branches:  [ "main" ]
  pull_request:
    branches:  [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [ self-hosted, "${{ matrix.os }}" ]

    strategy:
      fail-fast: false

      matrix:
        os: [ linux, windows ]
        build_type: [ Debug, Release ]
        c_compiler: [ gcc, cl ]
        include:
          - os: windows
            c_compiler: cl
            cpp_compiler: cl
          - os: linux
            c_compiler: gcc
            cpp_compiler: g++
        exclude:
          - os: windows
            c_compiler: gcc
          - os: linux
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: >
        cmake -B ${{ github.workspace }}/build
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}